version: '3.1'

services:
  application:
    image: biscuits-application
    ports:
      - 8080:8080
      - 8389:8389
    networks:
      - persistence
    environment:
      - MYSQL_HOST=mysql-database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=biscuits
      - MYSQL_ROOT_PASSWORD=secret
      - LDAP_BASE_DN=dc=unige,dc=ch
      - LDAP_PORT=8389
      - LDAP_LDIF_FILE=test-server.ldif
    restart: always
  
  database:
    image: mysql
    ports:
      - 3306:3306
    container_name: mysql-database
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=biscuits
    networks:
      - persistence
  
  # TODO : pass environment variables for java socket opening etc.
  snoopy-http-server:
    container_name: snoopy-http-server
    image: snoopy-http-server
    ports:
      - 8000:8000
    networks:
      - persistence
  
  snoopy-ldap-server:
    container_name: snoopy-ldap-server
    image: snoopy-ldap-server
    ports:
      - 1389:1389
    networks:
      - persistence

  snoopy-netcat-listener:
    container_name: snoopy-netcat-listener
    stdin_open: true
    tty: true
    command: -lvnp 9001
    image: snoopy-netcat-listener
    networks:
      - persistence

networks:
  persistence: